### ISSUE TITLE
Create unit-test for Mul.sv eqy

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#2302]
### Description

An attempt at creating a test was started [here](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2300), but a unit-test seems more approperiate.

A eqy unit-test can span synthesis and ORFS .tcl scripts, so it seems approperiate to have unit-tests with eqy in ORFS rather than in OpenROAD.

Tasks:

- [ ] How can Mul.sv in #2300 be best expressed as a fast eqy unit-test in ORFS and how are all steps covered? In particular it would be useful to have some unit-tests that start with checking synthesis.
- [ ] `. env.sh` and `make DESIGN_CONFIG=designs/asap7/mul/config.mk` in #2300 fails locally because eqy is not in the path, even though it is in dependencies/bin/eqy
- [ ] Hook up this test to CI
- [ ] Investigate the eqy failure that we're trying to study [here](https://github.com/The-OpenROAD-Project/bazel-orfs/pull/119), seems like this is a known problem in Yosys. https://github.com/YosysHQ/yosys/issues/3879 https://github.com/YosysHQ/yosys/pull/3882
- [ ] This is an attempt to rearticulate this test-case in ORFS speak: https://github.com/The-OpenROAD-Project/bazel-orfs/pull/119

### Suggested Solution

Not sure about the best way to test this in ORFS.

**Comment by oharboe** [comment]
@maliberty Per discussion, I think this is possibly a very obtuse one-off bug in Yosys, never seen anything like it, so it does not seem worth it to add a generic yosys eqy testing capability in ORFS.
